<a href="https://colab.research.google.com/github/MakineniSuryaTej/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing Library
import numpy as np

In [2]:
# Single Dimension array 
array1 = np.array([1, 2, 3, 4, 5])
print(array1, type(array1))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [3]:
# Multi Dimensional array
array2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array2, type(array2))

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


In [4]:
# Array elements filled or initialised with zeros
array3 = np.zeros((2, 3))
print(array3) 

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# Array elements filled with same number
array4 = np.full((4,4),5)
print(array4)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [7]:
# Intialize an array with a range
array5 = np.arange(10, 20)
array6 = np.arange(10, 40, 5)
print(array5, ",", array6)

[10 11 12 13 14 15 16 17 18 19] , [10 15 20 25 30 35]


In [9]:
# Initialize an array with random numbers
array7 = np.random.randint(100, 1000, 5)
print(array7)

[440 497 626 453 518]


In [10]:
# Chage shape
array8 = np.array([[1, 2, 3], [4, 5, 6]])
print(array8.shape)
array8.shape = (3,2)
print(array8.shape, array8)

(2, 3)
(3, 2) [[1 2]
 [3 4]
 [5 6]]


In [12]:
# Vertical stack
print(np.vstack((array1, array1)))

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [13]:
# Horizantal stack
print(np.hstack((array6, array6)))

[10 15 20 25 30 35 10 15 20 25 30 35]


In [14]:
# Column stack
print(np.column_stack((array6, array6)))

[[10 10]
 [15 15]
 [20 20]
 [25 25]
 [30 30]
 [35 35]]


In [17]:
# Intersection and Difference
array9 = np.array([10, 20, 30, 40, 50, 60])
array10 = np.array([50, 60, 70, 80, 90, 100])
print("Intersection is ", np.intersect1d(array9, array10))
print("Difference with respective first array ", np.setdiff1d(array9, array10))
print("Difference with respective second array ", np.setdiff1d(array10, array9))

Intersection is  [50 60]
Difference with respective first array  [10 20 30 40]
Difference with respective second array  [ 70  80  90 100]


In [19]:
# Addition
print(np.sum([array9, array10]))
print(np.sum([array9, array10], axis=0))
print(np.sum([array9, array10], axis=1))

660
[ 60  80 100 120 140 160]
[210 450]


In [20]:
# Basic mathematics on numpy arrays
print(array9 + 10)
print(array9 - 10)
print(array9 * 5)
print(array9 / 2)

[20 30 40 50 60 70]
[ 0 10 20 30 40 50]
[ 50 100 150 200 250 300]
[ 5. 10. 15. 20. 25. 30.]


In [22]:
# Mean, Median, Standard deviation
print("Mean is ", np.mean(array9))
print("Median is ", np.median(array9))
print("Standard Deviation is ", np.std(array9))

Mean is  35.0
Median is  35.0
Standard Deviation is  17.07825127659933


In [24]:
# Save and Load numpy
np.save('mynumpy',array9)
print(np.load('mynumpy.npy'))

[10 20 30 40 50 60]
